--SQL 5 Solutions 

-- 1) Report Contiguos Dates

WITH CTE AS (
	SELECT FAIL_DATE AS 'DATE1',
	'FAILED' AS PERIOD_STATE,
	RANK() OVER (ORDER BY FAIL_DATE) AS 'RNK' 
	FROM FAILED
	WHERE YEAR(FAIL_DATE) = 2019
	
	UNION ALL
	
	SELECT SUCCESS_DATE AS 'DATE1',
	'SUCCEEDED' AS PERIOD_STATE,
	RANK() OVER (ORDER BY SCUCCESS_DATE) AS 'RNK'
	FROM SUCCEEDED
	WHERE YEAR(SUCCESS_DATE) = 2019
)

SELECT PERIOD_STATE, MIN(DATE1) AS 'START_DATE', MAX(DATE1) AS 'END_DATE' 
FROM (
	SELECT *, (RANK() OVER(ORDER BY DATE1)) - RNK AS 'GROUP_RNK'
	FROM CTE
) AS Y 
GROUP BY GROUP_RNK,PERIOD_STATE
ORDER BY START_DATE;





--2) Student Report By Geography


SELECT America, Asia, Europe  FROM (
	(SELECT @AM := 0, @AS := 0, @EU := 0) T1, 
	(SELECT @AS := @AS + 1 AS 'ASRNK', NAME AS 'Asia' FROM STUDENT 
	WHERE CONTINENT = 'Asia'
	ORDER BY NAME) T2 RIGHT JOIN (
	SELECT @AM := @AM + 1 AS 'AMRNK', NAME AS 'America' FROM STUDENT 
	WHERE CONTINENT = 'America'
	ORDER BY NAME ) T3 ON ASRNK = AMRNK LEFT JOIN (
	SELECT @EU := @EU + 1 AS 'EURNK' , NAME AS 'Europe' FROM STUDENT
	WHERE CONTINENT = 'Europe'
	ORDER BY NAME 
	) T4 ON AMRNK=EURNK
);



--3) Average Salary Department vs Company

WITH DEPARTMENTSALARY AS (
	SELECT DEPARTMENT_ID, DATE_FORMAT( PAY_DATE, '%Y-%m') AS 'PAY_MONTH', AVG(AMOUNT) AS 'DEPARTMENTAVG' 
	FROM SALARY JOIN EMPLOYEE ON SALARY.EMPLOYEE_ID = EMPLOYEE.EMPLOYEE_ID
	GROUP BY DEPARTMENT_ID, PAY_MONTH
),
COMPANYSALARY AS (
	SELECT DATE_FORMAT(PAY_DATE, '%Y-%m') AS 'PAY_MONTH', AVG(AMOUNT) AS 'COMPANYAVG' 
	FROM SALARY 
	GROUP BY PAY_MONTH
)


SELECT DEPARTMENTSALARY.PAY_MONTH, DEPARTMENT_ID, (
	CASE
		WHEN DEPARTMENTAVG > COMPANYAVG THEN 'higher'
		WHEN DEPARTMENTAVG < COMPANYAVG THEN 'lower'
		ELSE 'same'
	END
) AS 'comparison' 
FROM  DEPARTMENTSALARY JOIN COMPANYSALARY
ON DEPARTMENTSALARY.PAY_MONTH = COMPANYSALARY.PAY_MONTH;



--4) Game Play Analysis I 
select player_id,min(event_date) as first_login
from Activity
group by player_id;

